### ISSUE TITLE
Set the supportFile config value to false (or add a support file)

### ISSUE THREAD

**Issue by natalia-davis-fu3e** [tuskr-app/cypress#1]
This project has no config file, so the test won't run and causes this error message:
```
Your project does not contain a default supportFile. We expect a file matching cypress/support/e2e.{js,jsx,ts,tsx} to exist.
If a support file is not necessary for your project, set supportFile to false.
https://on.cypress.io/support-file-missing-or-invalid
```

In **cypress.config.js**, please add this line inside the e2e block: `supportFile: false`
This'll allow the test to run. Alternatively, please add a support file.

Sincerely appreciate you guys adding Cypress integration to Tuskr, it's a much needed feature :)

**Comment by gtCeloxis** [comment]
Support files added, #a242209

**Comment by natalia-davis-fu3e** [comment]
Closed as resolved. Thank you!
